// <auto-generated />
namespace BlogSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class DialogsIsReadTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DialogsIsReadTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201505221510102_DialogsIsReadTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
